import pyautogui
import time
sleep = 1.5
time.sleep(sleep)
a = 0

while True:
    pyautogui.moveTo(290, 290)
    pyautogui.click()
    time.sleep(sleep)
    pyautogui.moveTo(1300, 700)
    pyautogui.click()
    time.sleep(sleep)
    pyautogui.moveTo(1150, 775)
    pyautogui.click()
    time.sleep(sleep)
    pyautogui.moveTo(646, 700)
    pyautogui.click()
    time.sleep(sleep)
    pyautogui.moveTo(1150, 775)
    pyautogui.click()
    time.sleep(sleep)
    pyautogui.moveTo(953, 618)
    pyautogui.click()
    time.sleep(sleep)
    pyautogui.moveTo(1150, 775)
    pyautogui.click()
    time.sleep(sleep)
    pyautogui.moveTo(290, 290)
    pyautogui.click()
    time.sleep(sleep)
    pyautogui.moveTo(1150, 950)
    pyautogui.click()
    time.sleep(sleep)
    pyautogui.moveTo(1150, 950)
    pyautogui.click()
    pyautogui.moveTo(1150, 950)
    pyautogui.click()
    time.sleep(sleep)
    time.sleep(sleep*4)
    a = a + 1
    if a == 15:
        pyautogui.moveTo(290, 290)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(290, 290)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(1700, 552)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(1152, 677)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(1300, 700)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(1150, 775)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(646, 700)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(1150, 775)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(953, 618)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(1150, 775)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(290, 290)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(1150, 950)
        pyautogui.click()
        time.sleep(sleep)
        pyautogui.moveTo(1150, 950)
        pyautogui.click()
        pyautogui.moveTo(1150, 950)
        pyautogui.click()
        time.sleep(sleep)
        time.sleep(sleep*4)
        a = 0

